In [1]:
import numpy as np
import scipy.linalg
import cvxpy as cp
from numpy.linalg import matrix_power

A Robust Learning Approach for Regression Models Based on Distributionally Robust Optimization

In [2]:
def dlqr(A,B,Q,R):
    """
    Calculates the optimal gain matrix K for system
    x[k+1] = A x[k] + B u[k]
    with cost = sum x[k].T*Q*x[k] + u[k].T*R*u[k], such that
    u[k] = -K x[k]
    
    Returns: 
        -K
    """
    # first, solve the ricatti equation
    P = np.matrix(scipy.linalg.solve_discrete_are(A, B, Q, R))
    # compute the LQR gain
    K = np.matrix(scipy.linalg.inv(B.T*P*B+R)*(B.T*P*A))
    return -K

In [3]:
def disc_linear_system(A,B,delta_t):
    '''
    Discrete a linear system with implicit Euler
    x[k+1] = (I - delta_t * A)^{-1} @ x[k] + (I - delta_t * A)^{-1} @ (delta_t * B) @ u[k]
    
    Returns:
        Ak
        Bk
    
    ''' 
    Nx = np.shape(A)[0]
    Ix = np.identity(Nx)
    
    Ak = np.linalg.inv(Ix - delta_t * A)
    Bk = np.linalg.inv(Ix - delta_t * A) @ (delta_t * B)
    
    
    return Ak, Bk

In [4]:
def RK4_np(f, x, u, t, h):
    """
    Runge-Kutta 4th order solver using numpy array data type.

    Args:
        f: A function returning first order ODE in 2D numpy array (Nx x 1).
        x: Current value (list or numpy array). 
        t: Current time.
        h: Step length.
    Returns:
        x_next: Vector of next value in 2D numpy array (Nx x 1)
    """
    x = np.reshape(x, (np.shape(x)[0], -1))    # Reshape x to col vector in np 2D array
    k1 = f(t, x, u)
    k2 = f(t + h / 2, x + h / 2 * k1, u)
    k3 = f(t + h / 2, x + h / 2 * k2, u)
    k4 = f(t + h, x + h * k3, u)
    x_next = x + h / 6 * (k1 + 2 * k2 + 2 * k3 + k4)
    return x_next

In [5]:
def mass_string_ode(t, x, u):
    m = 2 #[kg]
    k1 = 3 # [N/m]
    k2 = 2 # [N/m]
    
    A = np.array([[0,1],[-k2/m, -k1/m]])
    B = np.array([[0],[1/m]])
    
    dot_x = A @ x + B @ u
    
    return dot_x

In [6]:
def stack_system(A, B, C, D, E, x_init, N):
    '''
    Stack system matrix for N prediction horizon
    
    x_next = A x_k + B u_k + C w_k
    y_k = D x_k + E w_k
    
    '''

    n = np.shape(A)[1]    #  Dimension of state
    m = np.shape(B)[1]    #  Dimension of input
    d = np.shape(C)[1]    #  Dimension of disturbance
    r = np.shape(D)[0]    #  Dimension of output
    
#     print(Nx,Nu,Nw,Ny)
    Nx = (N+1) * n
    Nu = N * m
    Ny = N * r
    Nw = N * d
    
    Ax = np.zeros([Nx,n])
    Bx = np.zeros([Nx,Nu])
    Cx = np.zeros([Nx,Nw])
    Ay = np.zeros([Ny,n])
    By = np.zeros([Ny,Nu])
    Cy = np.zeros([Ny,Nw])
    Ey = np.zeros([Ny,Nw])
    Cx_tilde = np.zeros([Nx, Nw + 1])
    Cy_tilde = np.zeros([Ny + 1, Nw + 1])
    Ey_tilde = np.zeros([Ny + 1, Nw + 1])
    D_tilde = np.zeros([Ny + 1, Nx])
#     H

# Ax
    for i in range(N+1):
        Ax[i*n:(i+1)*n,:] = matrix_power(A,i)
# Bx
    for i in range(N):
        mat_temp = B
        for j in range (i+1):
            Bx[(i + 1) * n : (i + 2) * n, (i-j) * m: (i-j+1) * m ] = mat_temp
            mat_temp = A @ mat_temp
# Cx
    for i in range(N):
        mat_temp = C
        for j in range (i+1):
            Cx[(i + 1) * n : (i + 2) * n, (i-j) * d: (i-j+1) * d ] = mat_temp
            mat_temp = A @ mat_temp
# Ay
    for i in range(N):
        Ay[i*r:(i+1)*r,:] = D @ matrix_power(A,i) 
# By
    for i in range(N):
        mat_temp = B
        for j in range (i+1):
            By[(i + 1) * r : (i + 2) * r, (i-j) * m: (i-j+1) * m ] = D @ mat_temp
            mat_temp = A @ mat_temp
# Cy
    for i in range(N):
        mat_temp = C
        for j in range (i+1):
            Cy[(i + 1) * r : (i + 2) * r, (i-j) * d: (i-j+1) * d ] = D @ mat_temp
            mat_temp = A @ mat_temp
# Ey
    for i in range(N):
        Ey[i * r : (i+1)*r, i * d : (i+1) * d] = E
# Cx_tilde
    Cx_tilde[ : , 0 : 1 ] = Ax @ x_init
    Cx_tilde[ : , 1 : ] = Cx
# Cy_tilde
    Cy_tilde[ r : , 0 : 1 ] = Ay @ x_init
    Cy_tilde[ r : , 1 : ] = Cy
# Ey_tilde
    Ey_tilde[0, 0] = 1
    Ey_tilde[1:, 1:] = Ey
# D_tilde
    for i in range(N):
        D_tilde[1 + i * r : 1 + (i+1) * r, i * d : (i+1) * d] = D
        
    return n, m, d, r, Nx, Nu, Ny, Nw, Ax, Bx, Cx, Ay, By, Cy, Ey, Cx_tilde, Cy_tilde, Ey_tilde, D_tilde 

Continuous-time system

$\begin{aligned}\left[\begin{array}{c}\dot{x}_{1}(t) \\ \dot{x}_{2}(t)\end{array}\right] &=\left[\begin{array}{cc}0 & 1 \\ -k_{2} / m & -k_{1} / m\end{array}\right]\left[\begin{array}{l}x_{1}(t) \\ x_{2}(t)\end{array}\right]+\left[\begin{array}{c}0 \\ 1 / m\end{array}\right] u(t) \\ y(t) &=\left[\begin{array}{ll}1 & 0\end{array}\right]\left[\begin{array}{l}x_{1}(t) \\ x_{2}(t)\end{array}\right] \end{aligned}$

In [7]:
m = 2 #[kg]
k1 = 3 # [N/m]
k2 = 2 # [N/m]

para = [m, k1, k2]

x_init = np.array([[-2],[0]])

In [8]:
A = np.array([[0,1],[-k2/m, -k1/m]])
B = np.array([[0],[1/m]])
delta_t = 0.1

In [9]:
Ak,Bk = disc_linear_system(A,B,delta_t)

In [10]:
Ak

array([[ 0.99137931,  0.0862069 ],
       [-0.0862069 ,  0.86206897]])

In [11]:
Bk

array([[0.00431034],
       [0.04310345]])

In [12]:
Ck = np.array([[1e-3, 0],[0, 0]])
D = np.array([[1, 0]])
E = np.array([[0,1e-3]])

N = 5
n, m, d, r, Nx, Nu, Ny, Nw, Ax, Bx, Cx, Ay, By, Cy, Ey, Cx_tilde, Cy_tilde, Ey_tilde, D_tilde  = stack_system(Ak,Bk,Ck,D,E, x_init, N)

In [13]:
Q = np.diag([10,1])
Qf = np.diag([15,1])
R = np.diag([1])

In [14]:
neg_K = dlqr(Ak,Bk,Q,R)

In [15]:
neg_K

matrix([[-1.64465128, -1.02359576]])

In [16]:
N_sim = 100


t0 = 0

xk = x_init
uk = 0
t = t0
h = delta_t

x_list = []
x_list += [xk.flatten().tolist()]
u_list = []
for i in range(N_sim):
    wk = np.random.randn(d,1)    
    uk = neg_K @ xk
    u_list +=  uk.flatten().tolist() 
    x_kp1 = RK4_np(mass_string_ode, xk, uk, t, h)
    x_list += x_kp1.flatten().tolist()
    xk = x_kp1
    xk += Ck @ wk

In [17]:
u_list

[[3.289302564456352],
 [2.912520801444497],
 [2.5580641404413735],
 [2.224839003346022],
 [1.9135440685182106],
 [1.629753965539995],
 [1.367441287989381],
 [1.1319779626944977],
 [0.9213577108478626],
 [0.7326266131081962],
 [0.5674246400843805],
 [0.42236145023401894],
 [0.2957706774037503],
 [0.18785388915664059],
 [0.09579303226288305],
 [0.018256352151680755],
 [-0.04590990628268721],
 [-0.09745773675558622],
 [-0.13512806493716822],
 [-0.16612483297928754],
 [-0.187580763439543],
 [-0.20062599859876112],
 [-0.210145519107489],
 [-0.21267028093412835],
 [-0.21093808854502746],
 [-0.2040356808144727],
 [-0.19861603972183073],
 [-0.19289864794151884],
 [-0.18391093422001137],
 [-0.17113199947929764],
 [-0.15983754642649262],
 [-0.14741308044193627],
 [-0.13690302523936573],
 [-0.1201799684911536],
 [-0.10724493275723476],
 [-0.09383310791633678],
 [-0.08506142764151577],
 [-0.07413896863919461],
 [-0.06344898346093411],
 [-0.05576413691848042],
 [-0.04646935298694193],
 [-0.03700318

In [18]:
x_list

[[-2, 0],
 [-1.9826689238506545, 0.337883851188942],
 [-1.9335265036897336, 0.6079664862582865],
 [-1.8621290888978625, 0.8183799990124964],
 [-1.7721007851010764, 0.9764438399756508],
 [-1.6677179740839747, 1.0889189027419282],
 [-1.555901880400059, 1.1625564926589993],
 [-1.4365754037060634, 1.2029073677941833],
 [-1.315900193643724, 1.2155960887521764],
 [-1.1956294653429262, 1.2055567587542984],
 [-1.0765815591710686, 1.176995139954956],
 [-0.9619602148569422, 1.1339232694592156],
 [-0.8518350501871139, 1.0796594183780954],
 [-0.7469494159503197, 1.0170649268942489],
 [-0.6489319125878863, 0.9487754315763661],
 [-0.5574721448657889, 0.8769101206283618],
 [-0.4728835832565703, 0.8032688843167914],
 [-0.39541881152574204, 0.7293780963082022],
 [-0.32542851566888614, 0.6565554377510565],
 [-0.26436565759067554, 0.5861344501781512],
 [-0.2085903623158633, 0.5185938313931887],
 [-0.16008305377743243, 0.45466558791854955],
 [-0.11854808118222762, 0.39490259780953335],
 [-0.08133216802568

### System formulation
#### plant:

$$
\begin{aligned}
x_{k+1} &=A x_{k}+B u_{k} + C w_{k}\\
y_{k} &=D x_{k} + E w_{k}
\end{aligned}
$$
with $x_k \in \mathbb{R}^{n}, u_k \in \mathbb{R}^{m}, y_k \in \mathbb{R}^{r}, w_k \in \mathbb{R}^{d}$. Initial state $x_0$.


#### model:

$$
\begin{aligned}
\hat{x}_{k+1} &=A \hat{x}_{k}+B u_{k}\\
\hat{y}_{k} &=D \hat{x}_{k}
\end{aligned}
$$

Initial state $0$


### System behabior in N step
Define: $$
\boldsymbol{X}=\left[\begin{array}{llll}
x_{k}^{\top}, x_{k+1}^{\top} & \ldots & x_{k+N}^{\top}
\end{array}\right]^{\top}
$$
$$
\boldsymbol{U}=\left[\begin{array}{llll}
u_{k}^{\top} & u_{k+1}^{\top} & \ldots & u_{k+N-1}^{\top}
\end{array}\right]^{\top}
$$
$$
\boldsymbol{Y}=\left[\begin{array}{llll}
y_{k}^{\top} & y_{k+1}^{\top} & \ldots & y_{k+N-1}^{\top}
\end{array}\right]^{\top}
$$
$$
\boldsymbol{Y}_r=\left[\begin{array}{llll}
yr_{k}^{\top} & yr_{k+1}^{\top} & \ldots & yr_{k+N-1}^{\top}
\end{array}\right]^{\top}
$$

$$
\boldsymbol{W}=\left[\begin{array}{llll}
w_{k}^{\top} & w_{k+1}^{\top} & \ldots & w_{k+N-1}^{\top}
\end{array}\right]^{\top}
$$

$$
\tilde{\boldsymbol{W}}=\left[\begin{array}{llll}
1 & w_{k}^{\top} & \ldots & w_{k+N-1}^{\top}
\end{array}\right]^{\top}
$$

#### Predicted system
$$
\begin{array}{l}
\boldsymbol{X}=\mathcal{A}_{x} x_{k}+\mathcal{B}_{x} \boldsymbol{U} + \mathcal{C}_{x} \boldsymbol{W} \\
\boldsymbol{Y}=\mathcal{A}_{y} x_{k}+\mathcal{B}_{y} \boldsymbol{U} + \mathcal{C}_{y} \boldsymbol{W} + \mathcal{E}_{y} \boldsymbol{W}
\end{array}
$$
with
$$
\mathcal{A}_{x}=\left[\begin{array}{l}
\mathbb{I}_n \\ A^{1}\\  \vdots \\A^{N}
\end{array}\right]
$$

$$
\mathcal{B}_{x}=\left[\begin{array}{ccccc}
0 & 0 & \ldots & \ldots & 0\\
A^{0} B & 0 & \ldots & \ldots & 0 \\
A^{1} B & A^{0} B & \ddots & & \vdots \\
\vdots & \ddots & \ddots & \ddots & \vdots \\
\vdots & & \ddots & \ddots & 0 \\
A^{N-1} B & A^{N-2} B & \ldots & \ldots & A^{0} B
\end{array}\right]
$$

$$
\mathcal{C}_{x}=\left[\begin{array}{ccccc}
0 & 0 & \ldots & \ldots & 0\\
A^{0} C & 0 & \ldots & \ldots & 0 \\
A^{1} C & A^{0} C & \ddots & & \vdots \\
\vdots & \ddots & \ddots & \ddots & \vdots \\
\vdots & & \ddots & \ddots & 0 \\
A^{N-1} C & A^{N-2} C & \ldots & \ldots & A^{0} C
\end{array}\right]
$$

$$
\mathcal{A}_{y}=\left[\begin{array}{l}
D \\ DA^{1} \\ \vdots \\DA^{N-1}
\end{array}\right]
$$

$$
\mathcal{B}_{y}=\left[\begin{array}{cccccc}
0 & 0 & \ldots & \ldots & 0 & 0\\
DA^{0} B & 0 & \ldots & \ldots & 0 & 0\\
DA^{1} B & DA^{0} B & \ddots & & \vdots & 0\\
\vdots & \ddots & \ddots & \ddots & \vdots & 0\\
\vdots & & \ddots & \ddots & 0 & 0\\
DA^{N-2} B & DA^{N-3} B & \ldots & \ldots & DA^{0} B & 0
\end{array}\right]
$$

$$
\mathcal{C}_{y}=\left[\begin{array}{cccccc}
0 & 0 & \ldots & \ldots & 0 & 0\\
DA^{0} C & 0 & \ldots & \ldots & 0 & 0\\
DA^{1} C & DA^{0} C & \ddots & & \vdots & 0\\
\vdots & \ddots & \ddots & \ddots & \vdots & 0\\
\vdots & & \ddots & \ddots & 0 & 0\\
DA^{N-2} C & DA^{N-3} C & \ldots & \ldots & DA^{0} C & 0
\end{array}\right]
$$

$$
\mathcal{E}_{y} = \left[
  \begin{array}{ccc}
    E & & & & \\
    & \ddots & & & \\
    & & \ddots & & \\
    & & & \ddots & \\
    & & & & E
  \end{array} 
  \right]
$$


#### System with extended $\tilde{\boldsymbol{W}}$

$$
\begin{array}{l}
\boldsymbol{X}=\mathcal{B}_{x} \boldsymbol{U} + \tilde{\mathcal{C}}_{x} \tilde{\boldsymbol{W}} \\
\end{array}
$$

$$
\tilde{\mathcal{C}}_{x}=\left[\begin{array}{cccccc}
x_k & 0 & 0 & \ldots & \ldots & 0\\
A x_k & A^{0} C & 0 & \ldots & \ldots & 0 \\
A^2 x_k& A^{1} C & A^{0} C & \ddots & & \vdots \\
\vdots & \vdots & \ddots & \ddots & \ddots & \vdots \\
\vdots & \vdots & & \ddots & \ddots & 0 \\
A^N x_k & A^{N-1} C & A^{N-2} C & \ldots & \ldots & A^{0} C
\end{array}\right]
$$

#### puried-output-based (POB) affine control laws

$$
y - \hat{y} = \left(
\left[\begin{array}{c|cccc}
DA^0 x_0 & 0 & \dots & 0 & 0\\
DA^1 x_0 & DC & \ddots & 0 & 0\\
\vdots & \vdots & \ddots & \ddots & \vdots\\
DA^{N-1} x_0 & DA^{N-2}C & \dots & DA^{0}C & 0\\
\end{array}\right]
+
\left[\begin{array}{c|cccc}
0 & E & 0 & \dots & 0\\
0 & 0 & E & \ddots & 0\\
\vdots &  & \ddots & \ddots & 0\\
0 & 0 & \dots & 0 & E\\
\end{array}\right]
\right)
\left[\begin{array}{c}
1\\
w_0\\
w_1\\
\vdots\\
w_{N-1}\\
\end{array}\right]
$$




$u_{k}=h_{k}+\sum_{\tau=0}^{k} H_{k \tau} v_{\tau}$, where $v_{k} = y_k - \hat{y}_k$

$$
\begin{array}{rll}
u_k &= h_0 + H_{00} (y_k - \hat{y}_k) &= h_0 + H_{00} (Dx_0 +Ew_0)\\
u_{k+1} &= h_1 + H_{10} (y_k - \hat{y}_k) + H_{11} (y_{k+1} - \hat{y}_{k+1}) &= h_1 + H_{10} (Dx_0 +Ew_0) + H_{11} (DAx_0 + DCw_0 + E w_1) \\
\vdots &  & \vdots \\
u_{k+N-1} &= h_{N-1}+\sum_{\tau=0}^{N-1} H_{(N-1) \tau} v_{\tau} &= h_{N-1} +H_{(N-1) 0}(Dx_0 +Ew_0) + \dots + H_{(N-1) (N-1)} (DA^{N-1} x_0 + DA^{N-2}Cw_0 + \dots + DA^{0}Cw_{N-2}) + Ew_{N-1}
\end{array}
$$

$\rightarrow$

$$\boldsymbol{U} = 
\left[\begin{array}{c|cccc}
h_0 & H_{00} & \dots & 0 & 0\\
h_1 & H_{10} & \ddots & 0 & 0\\
\vdots & \vdots & \ddots & \ddots & \vdots\\
h_{N-1} & H_{(N-1)0} & \dots & H_{(N-1)(N-2)} & H_{(N-1)(N-1)}\\
\end{array}\right]
\left(
\left[\begin{array}{c|cccc}
0 & 0 & \dots & 0 & 0\\
DA^0 x_0 & 0 & \dots & 0 & 0\\
DA^1 x_0 & DC & \ddots & 0 & 0\\
\vdots & \vdots & \ddots & \ddots & \vdots\\
DA^{N-1} x_0 & DA^{N-2}C & \dots & DA^{0}C & 0\\
\end{array}\right]
+
\left[\begin{array}{c|cccc}
1 & 0 & \dots & 0 & 0\\
0 & E & 0 & \dots & 0\\
0 & 0 & E & \ddots & 0\\
\vdots &  & \ddots & \ddots & 0\\
0 & 0 & \dots & 0 & E\\
\end{array}\right]
\right)
\left[\begin{array}{c}
1\\
w_0\\
w_1\\
\vdots\\
w_{N-1}\\
\end{array}\right]
$$

$\rightarrow$
$$\boldsymbol{U} = \mathcal{H}(\tilde{\mathcal{C}}_y + \tilde{\mathcal{E}}_y) \tilde{\boldsymbol{W}} = H\tilde{\boldsymbol{W}} $$, where $ \tilde{\mathcal{C}}_y  = \left[\begin{array}{ccccc}
0 & & & & \\
D & 0 & & & \\
& D & 0 & & \\
& & \ddots & \ddots & \\
& & & D & 0
\end{array}\right] \tilde{\mathcal{C}}_x  = \tilde{\mathcal{D}} \tilde{C}_x$


#### Matrix shape
$\boldsymbol{X} \in \mathbb{R}^{(N+1)n \times 1} $,
$\boldsymbol{U} \in \mathbb{R}^{Nm \times 1} $,
$\boldsymbol{Y} \in \mathbb{R}^{Nr \times 1} $,
$\boldsymbol{W} \in \mathbb{R}^{Nd \times 1} $
$\tilde{\boldsymbol{W}} \in \mathbb{R}^{(Nd+1) \times 1} $

$\mathcal{A}_{x} \in \mathbb{R}^{(N+1)n \times n}$,
$\mathcal{B}_{x} \in \mathbb{R}^{(N+1)n \times Nm}$,
$\mathcal{C}_{x} \in \mathbb{R}^{(N+1)n \times Nd}$,
$\mathcal{A}_{y} \in \mathbb{R}^{Nr \times n}$,
$\mathcal{B}_{y} \in \mathbb{R}^{Nr \times Nm}$,
$\mathcal{C}_{y} \in \mathbb{R}^{Nr \times Nd}$,
$\mathcal{E}_{y} \in \mathbb{R}^{Nr \times Nd}$

$\tilde{\mathcal{C}}_{x} \in \mathbb{R}^{(N+1)n \times (Nd+1)}$, $\tilde{\mathcal{C}}_{y} \in \mathbb{R}^{(Nr + 1) \times (Nd+1)}$, $\tilde{\mathcal{E}}_{y} \in \mathbb{R}^{(Nr + 1) \times (Nd+1)}$, $\tilde{\mathcal{D}} \in \mathbb{R}^{(Nr + 1) \times (N+1)n}$

$\mathcal{H} \in \mathbb{R}^{Nm \times (Nr + 1)}$


### Cost
#### Weighted stage cost
$\beta^{t} (x_{k+t}^{\top} Q x_{k+t} + u_{k+t}^{\top} R u_{k+t} )$
#### Cost
$J_{N}\left(x, \pi_{N}\right):=\sup _{\mathbb{P} \in \mathcal{P}_{\infty}} \mathbb{E}_{\mathbb{P}}\left\{\sum_{t=0}^{N-1} \beta^{t}\left[\boldsymbol{x}_{t}^{\top} Q \boldsymbol{x}_{t}+\boldsymbol{u}_{t}^{\top} R \boldsymbol{u}_{t}\right]+\beta^{N} \boldsymbol{x}_{N}^{\top} Q_{f} \boldsymbol{x}_{N}\right\}$
#### Reformulation with known first and second moments
$$\boldsymbol{U} = \mathcal{H}(\tilde{\mathcal{C}}_y + \tilde{\mathcal{E}}_y) \tilde{\boldsymbol{W}} = H\tilde{\boldsymbol{W}}$$ and $$\boldsymbol{X}=\mathcal{B}_{x} \boldsymbol{U} + \tilde{\mathcal{C}}_{x} \tilde{\boldsymbol{W}}$$

$\tilde{J}_{N}(x, H):=\operatorname{Tr}\left\{\left[(\tilde{\mathcal{C}}_{x}+\mathcal{B}_{x}H)^{\top} J_{x} (\tilde{\mathcal{C}}_{x}+\mathcal{B}_{x}H) + H^{\top} J_u H \right]M_w\right\} + \mu_w^{\top} \left[ (\tilde{\mathcal{C}}_{x}+\mathcal{B}_{x}H)^{\top} J_{x} (\tilde{\mathcal{C}}_{x}+\mathcal{B}_{x}H) + H^{\top} J_u H \right]\mu_w$ with $J_x = \left[ \begin{array}{ccccc} \beta^{0}Q&&&&\\ &\beta^{1}Q&&&\\ &&\ddots&& \\ &&&\beta^{N-1}Q&\\ &&&&\beta^{N}Q_f \end{array}\right]$, $J_u = \left[ \begin{array}{cccc} \beta^{0}R&&&\\ &\beta^{1}R&&\\ &&\ddots& \\ &&&\beta^{N-1}R\end{array}\right]$, $M_{w}:=\left(1, \mu^{\top}, \ldots, \mu^{\top}\right)^{\top}\left(1, \mu^{\top}, \ldots, \mu^{\top}\right)+\operatorname{diag}\left(0, \mathbb{I}_{N} \otimes \mathbb{I}_{d}\right)$ and $\mu_w = \left[ \begin{array}{c} 1\\ \mu \\ \vdots \\ \mu \end{array} \right]$

### Chance constraint using wasserstein metric
Constraint on ith element of state: $[x_{k+n}]_i < v_{ubi}$


$\sup _{\mathbb{Q} \in \mathbb{B}_{\varepsilon}\left(\widehat{\mathbb{P}}_{N}\right)} \mathbb{E}^{\mathrm{Q}}[\ell(\xi)]$ with $l(w) = \max_{k \le N-1} \langle a_k, w\rangle + b_k$

equivalent to
$\begin{array}{lll}\inf _{\lambda, s_{i}, \gamma_{i k}} & \lambda \varepsilon+\frac{1}{N} \sum_{i=1}^{N} s_{i} \\ \text { s.t. } & b_{k}+\left\langle a_{k}, \widehat{\xi}_{i}\right\rangle+\left\langle\gamma_{i k}, d-C \widehat{\xi}_{i}\right\rangle \leq s_{i} & \forall i \leq N, \forall k \leq K \\ & \left\|C^{\top} \gamma_{i k}-a_{k}\right\|_{*} \leq \lambda & \forall i \leq N, \forall k \leq K \\ & \gamma_{i k} \geq 0 & \forall i \leq N, \forall k \leq K\end{array}$


#### Define $a_k$ and $b_k$
For example: Constraint on $[x_{k+1}]_1$

We have $x_{k+1} = Ax_0 + Bu_0 + Cw_0$ and $u_0 = h_0 + H_{00}(Dx_0 + Ew_0)$ $\rightarrow$ $[x_{k+1}]_1 = e_1^{\top} (Ax_0 + B(h_0 + H_{00}(Dx_0 + Ew_0)) + Cw_0) = \langle e_1^{\top} (BH_{00}E + C), w_0 \rangle  + e_1^{\top} (Ax_0 + B(h_0 + H_{00}Dx_0))$ 

Similiarly, $x_{k+N} = A^N x_0 + A^{N-1}Bu_0 + \dots + A^{0}Bu_{N-1} + A^{N-1}Cw_0 + \dots + A^{0}Cw_{N-1}$ and $u_{n}=h_{n}+\sum_{\tau=0}^{n} H_{n \tau} v_{\tau}$, where $v_{\tau} = y_{\tau} - \hat{y}_{\tau} = DA^{\tau}x_0 + DA^{\tau-1}Cw_0 + \dots + DA^{0}C w_{\tau-1} + E w_{\tau}$

$\rightarrow$ $[x_{k+N}]_i = e^{\top}_i (A^Nx_0 + \sum_{n=0}^{N-1}A^{n}B \underbrace{(h_{N-1-n} + \sum_{\tau = 0}^{N - 1 - n} ( H_{n\tau} \underbrace{( DA^{\tau}x_0 + \sum_{\kappa = 0}^{\tau-1} DA^{\kappa}Cw_{\tau-1 - \kappa} + Ew_{\tau})}_{v_\tau}))}_{u_{N- 1 - n}} + \sum_{n=0}^{N-1} A^{n}Cw_{N-1-n}) $

$ [x_{k+N}]_i = \langle e_i^{\top}(BH_{(N-1)(N-1)}E + C), w_{N-1} \rangle + e^{\top}_i (A^Nx_0 + \sum_{n=0}^{N-1}A^{n}B(h_{N-1-n} + \sum_{\tau = 0}^{N - 1 - n} ( H_{n\tau}( DA^{\tau}x_0 + \sum_{\kappa = 0}^{\tau-1} DA^{\kappa}Cw_{\tau-1 - \kappa}))) + \sum_{n=1}^{N-1} A^{n}Cw_{N-1-n})$

In [19]:
# def stack_system(A, B, C, D, E, x_init, N):
#     '''
#     Stack system matrix for N prediction horizon
    
#     x_next = A x_k + B u_k + C w_k
#     y_k = D x_k + E w_k
    
#     '''

#     n = np.shape(A)[1]    #  Dimension of state
#     m = np.shape(B)[1]    #  Dimension of input
#     d = np.shape(C)[1]    #  Dimension of disturbance
#     r = np.shape(D)[0]    #  Dimension of output
    
# #     print(Nx,Nu,Nw,Ny)
#     Nx = (N+1) * n
#     Nu = N * m
#     Ny = N * r
#     Nw = N * d
    
#     Ax = np.zeros([Nx,n])
#     Bx = np.zeros([Nx,Nu])
#     Cx = np.zeros([Nx,Nw])
#     Ay = np.zeros([Ny,n])
#     By = np.zeros([Ny,Nu])
#     Cy = np.zeros([Ny,Nw])
#     Ey = np.zeros([Ny,Nw])
#     Cx_tilde = np.zeros([Nx, Nw + 1])
#     Cy_tilde = np.zeros([Ny + 1, Nw + 1])
#     Ey_tilde = np.zeros([Ny + 1, Nw + 1])
#     D_tilde = np.zeros([Ny + 1, Nx])
# #     H

# # Ax
#     for i in range(N+1):
#         Ax[i*n:(i+1)*n,:] = matrix_power(A,i)
# # Bx
#     for i in range(N):
#         mat_temp = B
#         for j in range (i+1):
#             Bx[(i + 1) * n : (i + 2) * n, (i-j) * m: (i-j+1) * m ] = mat_temp
#             mat_temp = A @ mat_temp
# # Cx
#     for i in range(N):
#         mat_temp = C
#         for j in range (i+1):
#             Cx[(i + 1) * n : (i + 2) * n, (i-j) * d: (i-j+1) * d ] = mat_temp
#             mat_temp = A @ mat_temp
# # Ay
#     for i in range(N):
#         Ay[i*r:(i+1)*r,:] = D @ matrix_power(A,i) 
# # By
#     for i in range(N):
#         mat_temp = B
#         for j in range (i+1):
#             By[(i + 1) * r : (i + 2) * r, (i-j) * m: (i-j+1) * m ] = D @ mat_temp
#             mat_temp = A @ mat_temp
# # Cy
#     for i in range(N):
#         mat_temp = C
#         for j in range (i+1):
#             Cy[(i + 1) * r : (i + 2) * r, (i-j) * d: (i-j+1) * d ] = D @ mat_temp
#             mat_temp = A @ mat_temp
# # Ey
#     for i in range(N):
#         Ey[i * r : (i+1)*r, i * d : (i+1) * d] = E
# # Cx_tilde
#     Cx_tilde[ : , 0 : 1 ] = Ax @ x_init
#     Cx_tilde[ : , 1 : ] = Cx
# # Cy_tilde
#     Cy_tilde[ r : , 0 : 1 ] = Ay @ x_init
#     Cy_tilde[ r : , 1 : ] = Cy
# # Ey_tilde
#     Ey_tilde[0, 0] = 1
#     Ey_tilde[1:, 1:] = Ey
# # D_tilde
#     for i in range(N):
#         D_tilde[1 + i * r : 1 + (i+1) * r, i * d : (i+1) * d] = D
        
#     return n, m, d, r, Nx, Nu, Ny, Nw, Ax, Bx, Cx, Ay, By, Cy, Ey, Cx_tilde, Cy_tilde, Ey_tilde, D_tilde 

In [20]:
# Ck = np.array([[1e-3, 0],[0, 0]])
# D = np.array([[1, 0]])
# E = np.array([[0,1e-3]])

# N = 5
# n, m, d, r, Nx, Nu, Ny, Nw, Ax, Bx, Cx, Ay, By, Cy, Ey, Cx_tilde, Cy_tilde, Ey_tilde, D_tilde  = stack_system(Ak,Bk,Ck,D,E, x_init, N)

In [21]:
Ax

array([[ 1.        ,  0.        ],
       [ 0.        ,  1.        ],
       [ 0.99137931,  0.0862069 ],
       [-0.0862069 ,  0.86206897],
       [ 0.97540131,  0.15978002],
       [-0.15978002,  0.73573127],
       [ 0.95321854,  0.22182772],
       [-0.22182772,  0.62047696],
       [ 0.92587806,  0.2734048 ],
       [-0.2734048 ,  0.51577085],
       [ 0.89432697,  0.31551087],
       [-0.31551087,  0.42106066]])

In [22]:
Bx

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.00431034, 0.        , 0.        , 0.        , 0.        ],
       [0.04310345, 0.        , 0.        , 0.        , 0.        ],
       [0.007989  , 0.00431034, 0.        , 0.        , 0.        ],
       [0.03678656, 0.04310345, 0.        , 0.        , 0.        ],
       [0.01109139, 0.007989  , 0.00431034, 0.        , 0.        ],
       [0.03102385, 0.03678656, 0.04310345, 0.        , 0.        ],
       [0.01367024, 0.01109139, 0.007989  , 0.00431034, 0.        ],
       [0.02578854, 0.03102385, 0.03678656, 0.04310345, 0.        ],
       [0.01577554, 0.01367024, 0.01109139, 0.007989  , 0.00431034],
       [0.02105303, 0.02578854, 0.03102385, 0.03678656, 0.04310345]])

In [23]:
Cx

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.00000000e-03,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 9.91379310e-04,  0.00000000e+00,  1.00000000e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.

In [24]:
Ay

array([[1.        , 0.        ],
       [0.99137931, 0.0862069 ],
       [0.97540131, 0.15978002],
       [0.95321854, 0.22182772],
       [0.92587806, 0.2734048 ]])

In [25]:
By

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.00431034, 0.        , 0.        , 0.        , 0.        ],
       [0.007989  , 0.00431034, 0.        , 0.        , 0.        ],
       [0.01109139, 0.007989  , 0.00431034, 0.        , 0.        ],
       [0.01367024, 0.01109139, 0.007989  , 0.00431034, 0.        ]])

In [26]:
Cy

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.001     , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.00099138, 0.        , 0.001     , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.0009754 , 0.        , 0.00099138, 0.        , 0.001     ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.00095322, 0.        , 0.0009754 , 0.        , 0.00099138,
        0.        , 0.001     , 0.        , 0.        , 0.        ]])

In [27]:
Ey

array([[0.   , 0.001, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.001, 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.001]])

In [28]:
Cx_tilde

array([[-2.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-1.98275862e+00,  1.00000000e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.72413793e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-1.95080262e+00,  9.91379310e-04,  0.00000000e+00,
         1.00000000e-03,  0.00000000e+00,  0.00000000e+00,
  

In [29]:
Cy_tilde

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-2.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-1.98275862e+00,  1.00000000e-03,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-1.95080262e+00,  9.91379310e-04,  0.00000000e+00,
         1.00000000e-03,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-1.90643707e+00,  9.75401308e-04,  0.00000000e+00,
         9.91379310e-04,  0.00000000e+00,  1.00000000e-03,
  

In [30]:
Ey_tilde

array([[1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.001, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.001, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.001,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.001]])

In [31]:
D_tilde

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [32]:
def define_loss_func(m, d, r, Nu, Nw, Bx, Cx_tilde, mu, beta):
    # Define decision variables for POB affine constrol law
    
    sigma = 1 # var of normal distribution
    
    H_cal_dec = cp.Variable((Nu , 1))
#     print(H_cal_dec)
    # \mathcal{H} matrix
    for i in range(N):
        H_col = cp.Variable((Nu - (i * m) , r))
        if i > 0:
            H_col = cp.vstack([np.zeros([i * m, r]), H_col])
#         print(H_col)
        H_cal_dec = cp.hstack([H_cal_dec,H_col])
#     print(H_cal_dec)
#     print(np.shape(H_cal_dec))
    # Define intermediate decision variables for objective function
    H = cp.Variable((Nu , Nw + 1))
    
    # Define loss function
#     beta = 0.95
    Jx = np.zeros([(N+1)* n, (N+1)* n])
    for i in range(N):
        Jx[i * n : (i+1) * n, i * n : (i+1) * n] = beta**i * Q
    Jx[ N * n: , N * n:] = beta ** N * Qf

    Ju = np.zeros([N * m, N * m])
    for i in range(N):
        Ju[i * m : (i+1) * m, i * m : (i+1) * m] = beta**i * R

    # This is only for var = 1 and mean = 0. Should be modified.
    mu_w = np.vstack([1]+ [mu] * N)
#     M_w = mu_w @ mu_w.T + np.diag([0] + [1] * N * d)
    M_w = np.diag([1] + [(1-np.exp(-2*sigma**2))/2 ]* N * d)
    

    # Intermediate decision variables. Since CVXPY does not support quadratic obj of decision variable matrix.
    H_new_matrix = []
#     for i in range(Nw+1):
#         H_new_matrix += [cp.Variable([Nu,1])]
#     H_new = cp.hstack(H_new_matrix)
    for i in range(Nu):
        H_new_matrix += [cp.Variable([1, Nw+1])]
    H_new = cp.vstack(H_new_matrix)

#     print(H_new.shape)
    # Reformulate the quadratic term
    
    eigval,eigvec = np.linalg.eig(Ju + Bx.T @ Jx @ Bx)
    eigval_mat =  np.diag(eigval)
#     print(Ju + Bx.T @ Jx @ Bx - eigvec @ eigval_mat @ np.linalg.inv(eigvec))
    # Loss function
    loss_func = 0
    
    N_eig = np.shape(eigval)[0]
    I = np.diag([1]*(Nw+1))
    for i in range(N_eig):
        # Reformulate Tr(H.T @ (Ju + Bx.T @ Jx @ Bx)@ H ) @ M_w
#         print(np.shape(H_new_matrix[i].T))
        loss_func += eigval[i] * M_w[i,i] * cp.quad_form(H_new_matrix[i].T, I) # When M_w is identity matrix. Otherwise reformulate system matrix or this line
    loss_func += cp.trace(2 * Cx_tilde.T @ Jx @ Bx @ H @ M_w)
    # Reformulate mu_w.T @ (H.T @ (Ju + Bx.T @ Jx @ Bx)@ H ) @ mu_w
    loss_func += eigval[0] * cp.quad_form(H_new_matrix[i].T, I) +  2 * mu_w.T @  Cx_tilde.T @ Jx @ Bx @ H @ mu_w
    loss_func += cp.trace( Cx_tilde.T @ Jx @ Cx_tilde)
    
    return Jx, Ju, eigval,eigvec, H_cal_dec, H, H_new_matrix, H_new, loss_func

In [33]:
def gene_disturbance(N, d, N_sample):
    # Generate data 

    w_sample = []
    for i in range(N_sample):
        w_temp = np.sin(np.random.randn(N*d))
        w_sample += [w_temp]
    W_sample_matrix = np.array(w_sample).T

    W_sample_matrix_ext = np.vstack( [np.ones([1, N_sample]),W_sample_matrix])
    return W_sample_matrix, W_sample_matrix_ext

$$
\operatorname{Var} \sin X=\frac{1-e^{-2 \sigma^{2}}}{2}
$$

In [34]:
def define_constraint(W_sample_matrix, W_sample_matrix_ext, eigvec, H_cal_dec, H, H_new, n, Bx, Cx_tilde, Cy_tilde, Ey_tilde, i_th_state = 1, i_state_ub = 0.05, epsilon = 1, N_sample = 6):

    constraint = []
    constraint += [H_new == np.linalg.inv(eigvec) @ H ]
#     constraint += [H_new == eigvec.T @ H ]
    constraint += [H == H_cal_dec @ (Cy_tilde + Ey_tilde) ]
    
#     i_th_state = 1 # 0 for first element, 1 for second element
#     i_state_ub = 0.05

    d_supp = np.vstack( ( 1 * np.ones([N*d, 1]), 1 * np.ones([N*d, 1])))
    C_supp = np.vstack( (np.diag([1]*N*d), np.diag([-1]*N*d) ))

#     epsilon = 5 # select 20 best

    lambda_var = cp.Variable()

    gamma_shape = np.shape(d_supp)[0]
    gamma_matrix = []
    for i in range(N_sample):
        for j in range(N):
            gamma_var = cp.Variable([gamma_shape,1])
            gamma_matrix += [gamma_var]
    # k in N, i in N_sample
    #bk + <ak,xi_i>
    X_constraint = (Bx @ H_cal_dec @ (Cy_tilde + Ey_tilde) + Cx_tilde) @ W_sample_matrix_ext
    si_var = cp.Variable([N_sample,1])
    for i in range(N_sample):
        for j in range(N):
            constraint_temp = X_constraint[n * (j+1) + i_th_state,i] + gamma_matrix[i * N + j].T @ (d_supp - C_supp @ W_sample_matrix[:, i])
            constraint += [constraint_temp <= si_var[i,0]]


    ak_matrix = (Bx @ H_cal_dec @ (Cy_tilde + Ey_tilde) + Cx_tilde)[:,1:]
    for i in range(N_sample):
        for j in range(N):
            constraint_temp = C_supp.T @ gamma_matrix[i * N + j] - ak_matrix[n * (j+1) + i_th_state:n * (j+1)+i_th_state + 1,:].T
            constraint += [cp.norm_inf(constraint_temp) <= lambda_var]

    for i in range(N_sample):
        for j in range(N):
            constraint += [gamma_matrix[i * N + j] >= 0]
    constraint += [lambda_var * epsilon + 1/N_sample * cp.sum(si_var) <= i_state_ub]
    return lambda_var, gamma_matrix, si_var, constraint

In [35]:
def define_obj(n, m, d, r, Nu, Nw, Bx, Cx_tilde, Cy_tilde, Ey_tilde, mu, beta = 0.95, N_sample = 6, i_th_state = 1, i_state_ub = 0.05, epsilon = 1):
    Jx, Ju, eigval,eigvec, H_cal_dec, H, H_new_matrix, H_new, loss_func = define_loss_func(m, d, r, Nu, Nw, Bx, Cx_tilde, mu, beta)
    W_sample_matrix, W_sample_matrix_ext = gene_disturbance(N, d, N_sample)
    lambda_var, gamma_matrix, si_var, constraint = define_constraint(W_sample_matrix, W_sample_matrix_ext, eigvec, H_cal_dec, H, H_new, n, Bx, Cx_tilde, Cy_tilde, Ey_tilde, i_th_state, i_state_ub, epsilon, N_sample)
    return Jx, Ju, eigval,eigvec, H_cal_dec, H, H_new_matrix, H_new, loss_func, W_sample_matrix, W_sample_matrix_ext, lambda_var, gamma_matrix, si_var, constraint

In [36]:
mu =np.zeros([d,1])
mu_w = np.vstack([1]+ [mu] * N)
M_w = mu_w @ mu_w.T + np.diag([0] + [1] * N * d)
beta = 0.95
N_sample = 3
i_th_state = 1 
i_state_ub = 0.7
epsilon = 1

In [37]:
Jx, Ju, eigval,eigvec, H_cal_dec, H, H_new_matrix, H_new, loss_func, W_sample_matrix, W_sample_matrix_ext, lambda_var, gamma_matrix, si_var, constraint= define_obj(n, m, d, r, Nu, Nw, Bx, Cx_tilde, Cy_tilde, Ey_tilde, mu, beta = beta, N_sample = N_sample, i_th_state = i_th_state, i_state_ub = i_state_ub, epsilon = epsilon)

obj = cp.Minimize(loss_func)
prob = cp.Problem(obj,constraint)
# constraint
# prob.solve()

# lambda_var.value

# si_var.value

# np.sum(si_var.value)/N_sample + lambda_var.value * epsilon

# print(H_new_matrix[0].value)

# H_cal_dec.value

# np.trace(Cx_tilde.T @ Jx @ Cx_tilde) + mu_w.T @ Cx_tilde.T @ Jx @ Cx_tilde @mu_w

# np.trace(((Cx_tilde+Bx @ H.value).T @ Jx @ (Cx_tilde+Bx @ H.value) + H.value.T @ Ju @ H.value)@ M_w) + mu_w.T @ ((Cx_tilde+Bx @ H.value).T @ Jx @ (Cx_tilde+Bx @ H.value) + H.value.T @ Ju @ H.value) @ mu_w

# H.value @ W_sample_matrix_ext

# Ax @ x_init +  Bx @ H.value @ W_sample_matrix_ext[:,0:1]  + Cx @ W_sample_matrix[:,0:1]

# Cx_tilde

# H_cal_dec.value[0,0]

# H_cal_dec.value[0,1]

# 10 % 10 == 0

# x_init

# prob.value

In [ ]:
N_sim = 100


t0 = 0

xk = x_init
uk = 0
t = t0
h = delta_t



x_list = []
x_list += [xk.flatten().tolist()]
u_list = []
for i in range(N_sim):
#     if i % N == 0:
    n, m, d, r, Nx, Nu, Ny, Nw, Ax, Bx, Cx, Ay, By, Cy, Ey, Cx_tilde, Cy_tilde, Ey_tilde, D_tilde  = stack_system(Ak, Bk, Ck, D, E, xk, N)
    Jx, Ju, eigval,eigvec, H_cal_dec, H, H_new_matrix, H_new, loss_func, W_sample_matrix, W_sample_matrix_ext, lambda_var, gamma_matrix, si_var, constraint = define_obj(n, m, d, r, Nu, Nw, Bx, Cx_tilde, Cy_tilde, Ey_tilde, mu, beta = beta, N_sample = N_sample, i_th_state = i_th_state, i_state_ub = i_state_ub, epsilon = epsilon)
    obj = cp.Minimize(loss_func)
    prob = cp.Problem(obj,constraint)
#         print(W_sample_matrix)
#     print( prob.solve(verbose=True))
    prob.solve()
#         print(Ax @ x_init +  Bx @ H.value @ W_sample_matrix_ext[:,0:1]  + Cx @ W_sample_matrix[:,0:1])
#     print("status:", prob.status)
#         print("Controller", H_cal_dec.value[0,0], H_cal_dec.value[0,1])
#         print("lambda",lambda_var.value)
#         print("si",si_var.value)
#     print("state_constraint", np.sum(si_var.value)/N_sample + lambda_var.value * epsilon)
        
    wk = np.sin(np.random.randn(d,1))
    uk = H_cal_dec.value[0,0] + H_cal_dec.value[0,1] * (D @ xk + E @ wk)
    u_list +=  uk.flatten().tolist() 
    print(xk,uk)
    x_kp1 = RK4_np(mass_string_ode, xk, uk, t, h)
    x_list += x_kp1.flatten().tolist()
    xk = x_kp1
    xk += Ck @ wk

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cvxpy/problems/problem.py:1061: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  "Solution may be inaccurate. Try another solver, "


[[-2]
 [ 0]] [[1.32296646]]
[[-1.98794796]
 [ 0.24673752]] [[1.12515149]]
[[-1.95245655]
 [ 0.44770369]] [[0.88336466]]
[[-1.89858459]
 [ 0.6052699 ]] [[0.33614531]]
[[-1.8327785 ]
 [ 0.70981591]] [[-1.6218381]]
[[-1.76111675]
 [ 0.70246677]] [[-1.33198341]]
[[-1.69031523]
 [ 0.70296676]] [[-1.19963252]]
[[-1.61936303]
 [ 0.70296598]] [[-1.05816051]]
[[-1.54849774]
 [ 0.70294526]] [[-0.91553817]]
[[-1.47727172]
 [ 0.70296887]] [[-0.77347987]]
[[-1.4069796 ]
 [ 0.70297082]] [[-0.63308982]]
[[-1.33567811]
 [ 0.7029635 ]] [[-0.49059884]]
[[-1.26575083]
 [ 0.70295203]] [[-0.3509048]]
[[-1.19578084]
 [ 0.70293478]] [[-0.20895941]]
[[-1.12492864]
 [ 0.70301296]] [[-0.06932824]]
[[-1.05365985]
 [ 0.7029838 ]] [[0.07367153]]
[[-0.98363516]
 [ 0.70298025]] [[0.21463665]]
[[-0.91310588]
 [ 0.70301967]] [[0.3536459]]
[[-0.84306402]
 [ 0.70295842]] [[0.37413882]]
[[-0.77307047]
 [ 0.69736254]] [[0.32471529]]
[[-0.7036889 ]
 [ 0.68379161]] [[0.27851607]]
[[-0.63579513]
 [ 0.66359876]] [[0.23571314]

For x_init = np.array([[-1],[0]])
1. SolverError: Solver 'OSQP' failed. Try another solver, or solve with verbose=True for more information.
2. -inf   status: unbounded

In [ ]:
x_list