In [1]:
import numpy as np
# from DRO_model import Model_nonlinear
from DRO_model import Model
from DRO_optproblem import Opt_problem
# from DRO_simulation import Simulation_nonlinear
from DRO_simulation import Simulation
from scipy.linalg import expm
import mosek
import cvxpy as cp
import casadi as ca
import sys
import os

CSTR not used

<!-- ref: https://pdf.sciencedirectassets.com/314898/1-s2.0-S1474667004X70178/1-s2.0-S1474667017313228/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjELX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJGMEQCIE0nVSG6UtMhG4zgSKPd3N0n2H7T1T5FiqI0U22%2FI9oIAiBvnWpdWtMLu4JjkOAHpI3KlGEaCeJSCYM7oyewWJFmMyq0AwguEAMaDDA1OTAwMzU0Njg2NSIM1zIPzDW7SR7W3Q60KpEDkSo53nUXX9lUGfiBqFf%2Fay8v0we6wiLVFlowCa6hweDZxel9jWLrCRfE2w1bBwuCIWXgn5KjkoRn%2FpGi%2BDOoA3y2fX%2BmA%2Fw0ZxeLCLNYMSEurnHXXVNhyZv22cZI2hMnVhhZ3VMPNN9T%2F%2BPz81875aSP%2BIes%2BIqMut1zBaeUFy4y9YRmHc2DKmL7hSwbh9PDtV4AMl9dnSqS8vD%2BuiZJf3gTVDVlbkAOkMk3GiLwsz%2B56ypittmAlSEIkWsqXK7Qn3%2FxwAcV82WDSxoK568r49rnJPrDLQlytMzJjm0OQAr18XcFKzdNtFcIV3UhEFhIySSsVWDiuw1df9ilFFSRPX67WIOvRz5AfYdIhPoJGRnipYJIu9tr4Rk1%2BwW037WrUfH63OeFKPkjkylSwEKGItHwDwpU9GewH2m7InH8Ed%2F%2BJzfA0Mk2I8T%2BmrXTEjjSMYcSFPYd%2FavO4XKnAXmV3hfP59QF1GCE33mBvfqU9ExdVxYGNHssUmSgWKhsQ2i%2BiY2WB53mZPbihcfmAkrfFNYwkPKahAY67AGfDLvJVS1%2FHQLujrVAn%2BqhiY%2BDTTnJWMfL5qlBqigKH8PckHOLSnshans9C%2BEbLN0ZPng2BPEtiuNlUoXgsJcEc3xowv%2FQjz0v4AQhdRCN0x8QerjOGR%2F60AdrRtTGSdSbGJ5GseFASgt%2FgcPL9UNfVRTphdubZrXjTfOCD7a%2F%2FZj6T28ho1Xi2yc4%2FyHovSZokw9vPqWE7oeGFo9UrCsnNyefElHZ73z1XGUZrW1LYoSvbunNtE9x1mOtDI9OQDBpD9cidC1T%2F%2BGFt8hSZJOC10D%2BcPfEn9CvR1fVVmDClpKF2iOo1jGCpKqHHg%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210426T133648Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYUFUGSE4P%2F20210426%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=01980478c17f43665e94b1a1613919f5f71a3632119820588c9856d023029b1d&hash=606f42c607de6a0c3cf0ab25a0c274379db8ff609042baf7b585b6e338dbe7d7&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S1474667017313228&tid=spdf-8607abe8-9950-4b12-93ff-2af5ef7398e7&sid=e5dbdbd612a4a9407678a1488e09ae7368ddgxrqb&type=client
$\begin{aligned} \frac{d T}{d t}=& \frac{q_{f}}{V}\left(T_{f}-T\right)+K_{1} C e^{-\frac{E}{R T}}+K_{2} q_{c}\left(1-e^{-\frac{K_{3}}{q_{c}}}\right)\left(T_{c}-T\right) \\ \frac{d C}{d t}=& \frac{q_{f}}{V}\left(C_{f}-C\right)-K_{0} C e^{-\frac{k}{R T}} \end{aligned}$

$x=[T \quad C]^{T}$

$$
\begin{array}{l}
\Delta \dot{x}=\left[\begin{array}{ll}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{array}\right] \Delta x+\left[\begin{array}{l}
b_{1} \\
b_{2}
\end{array}\right] \Delta u \\
\Delta y=\left[\begin{array}{ll}
0 & 1
\end{array}\right] \Delta x
\end{array}
$$

$$
\begin{array}{l}
a_{11}=-\frac{q_{f}}{V}+K_{1} C \frac{E}{R T^{2}} e^{-\frac{E}{RT}}-K_{2} q_{c}\left(1-e^{-\frac{K_{3}}{q_c}}\right) \\
a_{12}=K_{1} e^{-\frac{E}{RT}} \\
a_{21}=-K_{0} C \frac{E}{R T^{2}} e^{-\frac{E}{R T}} \\
a_{22}=-\frac{q_{f}}{V}-K_{0} e^{-\frac{E}{R T}} \\
b_{1}=K_{2}\left(T_{c}-T\right)\left(1-e^{-\frac{K_{3}}{q_{c}}}\left(1+\frac{K_{3}}{q_{c}}\right)\right) \\
b_{2}=0
\end{array}
$$

$$
\begin{array}{ll}
\hline \text { var. } & \text { value } \\
\hline q_{f} & 100 \\
C_{f} & 1 \\
T_{f} & 350 \\
T_{c} & 350 \\
E / R & 10000 \\
V & 100 \\
K_{0} & 7.2 \cdot 10^{10} \\
K_{1} & 1.44 \cdot 10^{13} \\
K_{2} & 0.01 \\
K_{3} & 700
\end{array}
$$ -->

inverted pendulum ode not used
### System model
ref: https://www.researchgate.net/publication/273170289_Optimal_Control_of_Nonlinear_Inverted_Pendulum_System_Using_PID_Controller_and_LQR_Performance_Analysis_Without_and_With_Disturbance_Input

$\frac{\mathrm{d} \boldsymbol{x}}{\mathrm{d} t}=\frac{\mathrm{d}}{\mathrm{d} t}\left[\begin{array}{l}x_{1} \\ x_{2} \\ x_{3} \\ x_{4}\end{array}\right]=\frac{\mathrm{d}}{\mathrm{d} t}\left[\begin{array}{c}\theta \\ \dot{\theta} \\ x \\ \dot{x}\end{array}\right]=\left[\begin{array}{c}f_{1} \\ f_{2} \\ f_{3} \\ f_{4}\end{array}\right] = \left[\begin{array}{c} x_2\\ \frac{u \cos x_{1}-(M+m) g \sin x_{1}+m l\left(\cos x_{1} \sin x_{1}\right) x_{2}^{2}}{m l \cos ^{2} x_{1}-(M+m) l}  \\ x_4 \\ \frac{u+m l(\sin x_1) x_2^{2}-m g \cos x_1 \sin x_1}{M+m-m \cos ^{2} x_1} \end{array}\right]$

In [2]:
def inverted_pendulum_nonlinear_ode(x, u):
    M  = 2.4
    m = 0.23
    l = 0.36
    g = 9.81

    dx1_dt = x[1]
    dx2_dt = ( u * ca.cos(x[0]) - (M+m) * g * ca.sin(x[0]) + m * l * ca.cos(x[0]) *ca.sin(x[0])*x[1]**2) / (m*l*ca.cos(x[0])**2 - (M+m) *l)
    dx3_dt = x[3]
    dx4_dt = (u + m*l * ca.sin(x[0]) * x[1]**2 - m*g*ca.cos(x[0])*ca.sin(x[0]))/(M+m-m*ca.cos(x[0])**2)
    rhs = [dx1_dt,
           dx2_dt,
           dx3_dt,
           dx4_dt
           ]
    
    return ca.vertcat(*rhs)

In [ ]:
def inverted_pendulum_ode(t, x, u):
    M = 2.4
    m = 0.23
    l = 0.36
    g = 9.81

    dx1_dt = x[1]
    dx2_dt = (u * np.cos(x[0]) - (M + m) * g * np.sin(x[0]) + m * l * np.cos(x[0]) * np.sin(x[0]) * x[1] ** 2) / (
                m * l * np.cos(x[0]) ** 2 - (M + m) * l)
    dx3_dt = x[3]
    dx4_dt = (u + m * l * np.sin(x[0]) * x[1] ** 2 - m * g * np.cos(x[0]) * np.sin(x[0])) / (
                M + m - m * np.cos(x[0]) ** 2)
    rhs = [dx1_dt,
           dx2_dt,
           dx3_dt,
           dx4_dt
           ]

    return rhs

In [ ]:
def inverted_pendulum_linear_ode(x, u):
    
    

In [3]:
ode_A = ca.DM([[0, 1, 0, 0], 
 [29.8615, 0, 0, 0], 
 [0, 0, 0, 1], 
 [-0.9401, 0, 0, 0]])

In [4]:
ode_B = ca.DM([[0], [-1.15741], [0], [0.416667]])

In [32]:
if __name__ == "__main__":
    x_SX = ca.SX.sym("x_SX", 4)
    u_SX = ca.SX.sym("u_SX", 1)
    
    ode = ca.Function("ode_func", [x_SX, u_SX], [inverted_pendulum_ode(x_SX, u_SX)])
    ode = ca.Function("ode_func",[x_SX, u_SX],[ode_A @ x_SX + ode_B @ u_SX])
    delta_t = 0.06
    N = 5

In [33]:
    # x_init = np.array([[0], [0], [-np.pi/2], [0]])
    x_init = np.array([[-0.5], [0], [0], [0]])
    u_init =  np.array([[0]])
    # C = np.diag([0, 0, 0, 1e-2])
    # C = np.array([[0, 0],[0, 0],[1e-2, 0],[0, 0]])
    C = np.array([[0, 0],[1e-2, 0],[0, 0],[0, 0]])
    D = np.array([[1, 0,0 , 0]])
    # D = np.array([[1, 0, 0, 0], [0,0,1,0]])
    E = np.array([[0, 1e-2]])
    # E = np.array([[0, 0, 1e-2, 0]])
    N = 5
    model = Model_nonlinear(ode, C, D, E, x_init,u_init, N, delta_t)


In [34]:
model.ode_disc_func([0,0,0,0],[0])

DM([0, 0, 0, 0])

In [35]:
model.jacobian_disc_x([0,0,0,0],[0])

DM(
[[1.05423, 0.061075, 00, 00], 
 [1.82379, 1.05423, 00, 00], 
 [-0.00170734, -3.38436e-05, 1, 0.06], 
 [-0.0574166, -0.00170734, 00, 1]])

In [36]:
model.jacobian_ode_x([0,0,0,0],[0])

AttributeError: 'Model_nonlinear' object has no attribute 'jacobian_ode_x'

In [37]:
model.jacobian_ode_u([0,0,0,0],[0])

AttributeError: 'Model_nonlinear' object has no attribute 'jacobian_ode_u'

In [38]:
Q = np.diag([1000, 1, 1500, 1])
Qf = np.diag([1000, 1, 1500, 1])
R = np.diag([1])

d = model.d
mu = np.zeros([d, 1])
sigma = 1
beta = 0.95
N_sample = 3
i_th_state = 1
i_state_ub = 0.4
epsilon = 1

sin_const = 3
N_sim = 100
sim = Simulation_nonlinear(model, Q, Qf, R, x_init, beta = beta, N_sample = N_sample, i_th_state = i_th_state, i_state_ub = i_state_ub, epsilon = epsilon,
sin_const = sin_const, N_sim=N_sim, mode = "gene", mu = mu, sigma = sigma, est = False)
print(sim.x_sim)
sim.plot_state()

[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000000e+00]]
current state and input [[-0.48938404]
 [ 0.33544095]
 [-0.0126198 ]
 [-0.42075878]] [[-17.95054352]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000000e+00]]
current state and input [[-0.46936915]
 [ 0.36648252]
 [-0.04634964]
 [-0.70375919]] [[-12.4016181]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000

current state and input [[-1.75792214]
 [-3.44160772]
 [-4.17213158]
 [-7.9499494 ]] [[-37.60175947]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000000e+00]]
current state and input [[-1.97470888]
 [-3.83826139]
 [-4.67770018]
 [-8.90028247]] [[-42.21953555]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000000e+00]]
current state and input [[-2.21662344]
 [-4.26902762]
 [-5.24378122]
 [-9.96679234]] [[-47.3834876]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38

current state and input [[-21.78304045]
 [-41.71000914]
 [-51.30832465]
 [-97.4237593 ]] [[-466.37228252]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000000e+00]]
current state and input [[ -24.41328227]
 [ -46.73456763]
 [ -57.50741718]
 [-109.18772745]] [[-522.61632157]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000000e+00]]
current state and input [[ -27.36062283]
 [ -52.40085846]
 [ -64.45497194]
 [-122.369495  ]] [[-585.61346996]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]

current state and input [[ -267.68919557]
 [ -512.79321335]
 [ -630.60290236]
 [-1197.06311823]] [[-5731.33448036]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000000e+00]]
current state and input [[ -300.0232638 ]
 [ -574.75050681]
 [ -706.7736865 ]
 [-1341.65654085]] [[-6423.48006084]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+00  0.00000000e+00]
 [-1.70733931e-03 -3.38436000e-05  1.00000000e+00  6.00000000e-02]
 [-5.74166207e-02 -1.70733931e-03  0.00000000e+00  1.00000000e+00]]
current state and input [[ -336.26387707]
 [ -644.18626388]
 [ -792.14519205]
 [-1503.7168034 ]] [[-7199.42905433]]
[[ 1.05423222e+00  6.10750140e-02  0.00000000e+00  0.00000000e+00]
 [ 1.82379153e+00  1.05423222e+00  0.00000000e+

ValueError: Cannot unpack invalid solution: Solution(status=UNKNOWN, opt_val=nan, primal_vars={}, dual_vars={}, attr={'solve_time': 0.03877902030944824})

In [79]:
M  = 0.5
m = 0.2
l = 0.3
b = 0.1
g = 9.8
I = 0.006

p = I * (M + m) + M * m * l ** 2

A = np.array([[0, 1, 0, 0],
              [0, -(I+m*l**2)*b/p,  (m**2*g*l**2)/p,   0],
              [0, 0, 0, 1],
              [0, -(m*l*b)/p,       m*g*l*(M+m)/p,  0]])
B = np.array([[0], [(I+m*l**2)/p], [0], [m*l/p]])

In [80]:
def disc_linear_system1(A, B, delta_t,n):
    '''
    '''

    Ak = expm(A*delta_t)
    Bk = (expm(A * delta_t) - np.identity(n)) @ np.linalg.inv(A) @ B

    return Ak, Bk

In [81]:
delta_t = 0.01
disc_linear_system1(A,B,delta_t,4)

LinAlgError: Singular matrix

In [76]:
def disc_linear_system2(A, B, delta_t,n):
    '''
    Discrete a linear system with implicit Euler
    x[k+1] = (I - delta_t * A)^{-1} @ x[k] + (I - delta_t * A)^{-1} @ (delta_t * B) @ u[k]

    Returns:
        Ak
        Bk

    '''
    Nx = np.shape(A)[0]
    Ix = np.identity(Nx)

    Ak = np.linalg.inv(Ix - delta_t * A)
    Bk = np.linalg.inv(Ix - delta_t * A) @ (delta_t * B)

    return Ak, Bk

In [77]:
disc_linear_system2(A,B,delta_t,4)

(array([[ 1.00000000e+00,  9.98183904e-03,  2.67621828e-04,
          2.67621828e-06],
        [ 0.00000000e+00,  9.98183904e-01,  2.67621828e-02,
          2.67621828e-04],
        [ 0.00000000e+00, -4.55139163e-05,  1.00312672e+00,
          1.00312672e-02],
        [ 0.00000000e+00, -4.55139163e-03,  3.12671502e-01,
          1.00312672e+00]]),
 array([[0.00018161],
        [0.01816096],
        [0.00045514],
        [0.04551392]]))

## Begins here

In [2]:
import numpy as np
from DRO_model import Model_nonlinear
from DRO_optproblem import Opt_problem
from DRO_simulation import Simulation_nonlinear
from scipy.linalg import expm
import mosek
import cvxpy as cp
import casadi as ca
import sys
import os


def inverted_pendulum_nonlinear_ode(x, u):
    M = 2.4
    m = 0.23
    l = 0.36
    g = 9.81

    dx1_dt = x[1]
    dx2_dt = (u * ca.cos(x[0]) - (M + m) * g * ca.sin(x[0]) + m * l * ca.cos(x[0]) * ca.sin(x[0]) * x[1] ** 2) / (
                m * l * ca.cos(x[0]) ** 2 - (M + m) * l)
    dx3_dt = x[3]
    dx4_dt = (u + m * l * ca.sin(x[0]) * x[1] ** 2 - m * g * ca.cos(x[0]) * ca.sin(x[0])) / (
                M + m - m * ca.cos(x[0]) ** 2)
    rhs = [dx1_dt,
           dx2_dt,
           dx3_dt,
           dx4_dt
           ]

    return ca.vertcat(*rhs)


if __name__ == "__main__":
    x_SX = ca.SX.sym("x_SX", 4)
    u_SX = ca.SX.sym("u_SX", 1)

    ode = ca.Function("ode_func", [x_SX, u_SX], [inverted_pendulum_nonlinear_ode(x_SX, u_SX)])
    delta_t = 0.5
    N = 5

    # x_init = np.array([[0], [0], [-np.pi/2], [0]])
    x_init = np.array([[-0.5], [0], [0], [0]])
    u_init =  np.array([[0]])
    # C = np.diag([0, 0, 0, 1e-2])
    # C = np.array([[0, 0],[0, 0],[1e-2, 0],[0, 0]])
    C = np.array([[0, 0],[1e-2, 0],[0, 0],[0, 0]])
    D = np.array([[1, 0,0 , 0]])
    # D = np.array([[1, 0, 0, 0], [0,0,1,0]])
    E = np.array([[0, 1e-2]])
    # E = np.array([[0, 0, 1e-2, 0]])
    N = 5
    model = Model_nonlinear(ode, C, D, E, x_init,u_init, N, delta_t)

    Q = np.diag([1500, 1, 1000, 1])
    Qf = np.diag([1500, 1, 1000, 1])
    R = np.diag([1])

    d = model.d
    mu = np.zeros([d, 1])
    sigma = 1
    beta = 0.95
    N_sample = 1
    i_th_state = 1
    i_state_ub = 0.2
    epsilon = 10

    sin_const = 3
    N_sim = 50
    sim = Simulation_nonlinear(model, Q, Qf, R, x_init, beta=beta, N_sample=N_sample, i_th_state=i_th_state,
                               i_state_ub=i_state_ub, epsilon=epsilon,
                               sin_const=sin_const, N_sim=N_sim, mode="gene", mu=mu, sigma=sigma, est=False)
    print(sim.x_sim)
    sim.plot_state()


current state and input [[-0.5]
 [ 0. ]
 [ 0. ]
 [ 0. ]] [[-15.74830826]]


TypeError: can't multiply sequence by non-int of type 'float'