In [7]:
import numpy as np
from DRO_model import Model
from DRO_optproblem import Opt_problem
from DRO_simulation import Simulation
import mosek
import cvxpy as cp
import sys
import os

In [2]:
def mass_string_ode(t, x, u):
    m = 2  # [kg]
    k1 = 3  # [N/m]
    k2 = 2  # [N/m]

    A = np.array([[0, 1], [-k2 / m, -k1 / m]])
    B = np.array([[0], [1 / m]])

    dot_x = A @ x + B @ u

    return dot_x

In [3]:
if __name__ == "__main__":

    m = 2 #[kg]
    k1 = 3 # [N/m]
    k2 = 2 # [N/m]

    A = np.array([[0,1],[-k2/m, -k1/m]])
    B = np.array([[0],[1/m]])
    delta_t = 0.1

    x_init = np.array([[-2],[0]])


    Ck = np.array([[1e-3, 0],[0, 0]])
    D = np.array([[1, 0]])
    E = np.array([[0,1e-3]])
    N = 5

    model = Model(A, B, Ck, D, E, x_init, N, delta_t)


    Q = np.diag([10, 1])
    Qf = np.diag([15, 1])
    R = np.diag([1])

    d = model.d
    mu = np.zeros([d, 1])
    mu_w = np.vstack([1] + [mu] * N)
    M_w = mu_w @ mu_w.T + np.diag([0] + [1] * N * d)
    beta = 0.95
    N_sample = 3
    i_th_state = 1
    i_state_ub = 0.5
    epsilon = 1
    sin_const = 2
    N_sim = 10

    sim = Simulation(model, Q, Qf, R, mu, x_init, beta = beta, N_sample = N_sample, i_th_state = i_th_state, i_state_ub = i_state_ub, epsilon = epsilon,
    sin_const = sin_const, N_sim=N_sim, mode = "gene")
    print(sim.x_sim)

current state and input [[-2]
 [ 0]] [[0.27197548]]
current state and input [[-1.97999203]
 [ 0.18413687]] [[0.05590207]]
current state and input [[-1.94697882]
 [ 0.33183722]] [[-0.42046986]]
current state and input [[-1.90141221]
 [ 0.43578587]] [[-0.31739109]]
current state and input [[-1.84776639]
 [ 0.52591167]] [[-3.91551621]]
current state and input [[-1.80503012]
 [ 0.44389009]] [[-0.96238658]]
current state and input [[-1.75446001]
 [ 0.49678773]] [[-2.07285632]]
current state and input [[-1.70349509]
 [ 0.49016458]] [[-1.65274757]]
current state and input [[-1.65392896]
 [ 0.49816958]] [[-1.74965191]]
current state and input [[-1.60612852]
 [ 0.49662059]] [[-2.91280426]]
[-2, 0, -1.9815863125768518, 0.18413687423148234, -1.94680830805858, 0.33183722488226447, -1.9034002282602986, 0.4357858736317001, -1.8488210383175094, 0.5259116719638951, -1.8033773812150113, 0.4438900867837744, -1.7553513504186926, 0.49678773299269813, -1.7054435543604254, 0.4901645848134224, -1.65367813029

In [5]:
sys.path

['/Users/zhengangzhong/Dropbox/code/py/optimization/distributionally_robust_optimization',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',
 '',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages',
 '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/extensions',
 '/Users/zhengangzhong/.ipython']

In [11]:
file_name =(os.path.splitext(sys.argv[0])[0]).split("/")[-1]
write_path = "/Users/zhengangzhong/Dropbox/PhD/documents/paper_writing/CDC2021/result/" + file_name +".txt"
with open(write_path, 'w') as f:
#     for listitem in result_T:
    f.write('%s\n' % "1")
f.close()

In [23]:
epsilon = 0.01

temp = str(epsilon).split(".")
temp

['0', '01']

In [188]:
def gene_sample(N, d, N_sample, sin_const):
    # Generate data: const * sinx

    w_sample = []
    for i in range(N_sample * N):
        w_temp = sin_const * np.sin(np.random.randn(d, 1))
        w_sample += [w_temp]
    return w_sample
N = 3
d = 2 
N_sample = 50
sin_const = 2
data_set = gene_sample(N, d, N_sample, sin_const)

In [189]:
data_set

[array([[-1.99749931],
        [ 0.76025871]]),
 array([[-1.95353138],
        [ 1.09092276]]),
 array([[-1.81118165],
        [-1.3193738 ]]),
 array([[ 1.71876763],
        [-0.9644791 ]]),
 array([[-1.90195498],
        [ 1.91433636]]),
 array([[-1.37744139],
        [ 1.97536313]]),
 array([[-0.63996284],
        [-1.34046606]]),
 array([[ 0.96309208],
        [-1.11732783]]),
 array([[1.60222298],
        [0.47754758]]),
 array([[1.99467493],
        [0.78167454]]),
 array([[1.56315171],
        [1.54908608]]),
 array([[ 1.91611206],
        [-0.97025459]]),
 array([[-1.38431151],
        [-1.9950606 ]]),
 array([[ 1.92782963],
        [-1.99862918]]),
 array([[-0.87994126],
        [-0.78820279]]),
 array([[1.93665769],
        [1.44865716]]),
 array([[ 0.05064599],
        [-0.42325069]]),
 array([[ 1.74223168],
        [-1.37033645]]),
 array([[ 1.57874885],
        [-1.91879194]]),
 array([[ 1.5747222 ],
        [-1.30805429]]),
 array([[-0.85849677],
        [-1.98876746]]),


In [190]:
W_sample_matrix = np.vstack(data_set)
W_sample_matrix

array([[-1.99749931],
       [ 0.76025871],
       [-1.95353138],
       [ 1.09092276],
       [-1.81118165],
       [-1.3193738 ],
       [ 1.71876763],
       [-0.9644791 ],
       [-1.90195498],
       [ 1.91433636],
       [-1.37744139],
       [ 1.97536313],
       [-0.63996284],
       [-1.34046606],
       [ 0.96309208],
       [-1.11732783],
       [ 1.60222298],
       [ 0.47754758],
       [ 1.99467493],
       [ 0.78167454],
       [ 1.56315171],
       [ 1.54908608],
       [ 1.91611206],
       [-0.97025459],
       [-1.38431151],
       [-1.9950606 ],
       [ 1.92782963],
       [-1.99862918],
       [-0.87994126],
       [-0.78820279],
       [ 1.93665769],
       [ 1.44865716],
       [ 0.05064599],
       [-0.42325069],
       [ 1.74223168],
       [-1.37033645],
       [ 1.57874885],
       [-1.91879194],
       [ 1.5747222 ],
       [-1.30805429],
       [-0.85849677],
       [-1.98876746],
       [-0.60084273],
       [ 0.81682365],
       [ 1.9819072 ],
       [-1

In [191]:
W_sample_matrix = np.vstack(data_set[- N * N_sample:])
W_sample_matrix

array([[-1.99749931],
       [ 0.76025871],
       [-1.95353138],
       [ 1.09092276],
       [-1.81118165],
       [-1.3193738 ],
       [ 1.71876763],
       [-0.9644791 ],
       [-1.90195498],
       [ 1.91433636],
       [-1.37744139],
       [ 1.97536313],
       [-0.63996284],
       [-1.34046606],
       [ 0.96309208],
       [-1.11732783],
       [ 1.60222298],
       [ 0.47754758],
       [ 1.99467493],
       [ 0.78167454],
       [ 1.56315171],
       [ 1.54908608],
       [ 1.91611206],
       [-0.97025459],
       [-1.38431151],
       [-1.9950606 ],
       [ 1.92782963],
       [-1.99862918],
       [-0.87994126],
       [-0.78820279],
       [ 1.93665769],
       [ 1.44865716],
       [ 0.05064599],
       [-0.42325069],
       [ 1.74223168],
       [-1.37033645],
       [ 1.57874885],
       [-1.91879194],
       [ 1.5747222 ],
       [-1.30805429],
       [-0.85849677],
       [-1.98876746],
       [-0.60084273],
       [ 0.81682365],
       [ 1.9819072 ],
       [-1

In [192]:
W_sample_matrix = np.vstack(data_set)
W_sample_matrix = W_sample_matrix.T.reshape(d, -1, order='F')
W_sample_matrix

array([[-1.99749931, -1.95353138, -1.81118165,  1.71876763, -1.90195498,
        -1.37744139, -0.63996284,  0.96309208,  1.60222298,  1.99467493,
         1.56315171,  1.91611206, -1.38431151,  1.92782963, -0.87994126,
         1.93665769,  0.05064599,  1.74223168,  1.57874885,  1.5747222 ,
        -0.85849677, -0.60084273,  1.9819072 , -1.46155164, -1.5767276 ,
         0.59455098, -0.36430487, -0.79628551, -1.9290215 , -1.99065995,
         0.88515207,  1.86129089,  1.63015399, -1.11388069,  1.3215991 ,
         1.18690338,  0.97655599,  1.95112236,  1.974147  , -0.18519436,
         1.45171623,  0.93991983,  1.99962249,  0.00273394,  0.54780125,
         0.02258952, -1.96308664,  0.41212206, -0.20204155, -1.95531794,
         0.10473127,  1.94153839,  0.47718211,  0.35414372,  0.20720968,
        -0.82741062, -1.60473393,  1.75441237,  0.60042029, -0.0943006 ,
        -0.09861991, -1.62084564, -1.49970931,  1.7008613 , -0.63790656,
        -0.03376522, -1.37494729, -1.69636084,  1.3

In [193]:
np.var(W_sample_matrix,axis = 1, ddof = 0)

array([1.90620083, 1.51892199])

In [194]:
np.var(W_sample_matrix,axis = 1, ddof = 1)

array([1.91899413, 1.5291161 ])

In [195]:
mean = np.mean(W_sample_matrix,axis = 1).reshape(-1,1)
mean

array([[ 0.22165454],
       [-0.13653099]])

In [196]:
np.vstack([1] + [mean] * N)

array([[ 1.        ],
       [ 0.22165454],
       [-0.13653099],
       [ 0.22165454],
       [-0.13653099],
       [ 0.22165454],
       [-0.13653099]])